---

name: gcp.labbox-deploy

trigger: none

variables:
# - template: release/variables.yml
  - group: gcp.labrink72.vars
  - name: gcpKeyData
    value: $[variables.pipelineautomationkeyfile]

resources:
  repositories:
    - repository: infrastructure
      type: github
      name: rink72/lab-infrastructure
      ref: refs/tags/0.2.0
      endpoint: rink72

    - repository: templates
      type: github
      name: rink72/lab-templates
      ref: refs/heads/first-version
      endpoint: rink72


# steps:
#   - checkout: self
#   - checkout: infrastructure
#   - checkout: templates
#   - pwsh: Write-Host Hello
#     displayName: Say hello
#     name: firstStep

stages:
  - stage: Deploy
    displayName: Infrastructure deploy
    jobs:
    - template: templates/jobs/infrastructure-deploy.yml@templates
      parameters:
        cloudType: GCP
        service: labbox
        gcpKeyData: $(gcpKeyData)