---

name: gcp.labbox-deploy

trigger: none

pool:
  vmImage: windows-latest

variables:
  - group: gcp.labrink72.vars
  - name: gcpKeyData
    value: $[variables.pipelineautomationkeyfile]

parameters:
  - name: apply
    displayName: Apply configuration
    type: boolean
    defaultValue: false

resources:
  repositories:
    - repository: infrastructure
      type: github
      name: rink72/lab-infrastructure
      #ref: refs/tags/0.2.0
      ref: refs/heads/convert-to-static-environment
      endpoint: rink72

    - repository: templates
      type: github
      name: rink72/lab-templates
      ref: refs/heads/first-version
      endpoint: rink72

stages:
  - stage: Deploy
    displayName: Infrastructure deploy
    jobs:
    - template: templates/jobs/infrastructure-deploy.yml@templates
      parameters:
        cloudType: GCP
        service: labbox
        gcpKeyData: $(gcpKeyData)
        apply: ${{ parameters.apply }}