---

name: gcp.labbox-deploy

trigger: none

pool:
  vmImage: windows-latest

# variables:
# - template: release/variables.yml

resources:
  repositories:
    - repository: infrastructure
      type: github
      name: rink72/lab-infrastructure
      ref: refs/tags/0.2.0
      endpoint: rink72

    - repository: templates
      type: github
      name: rink72/lab-templates
      #ref: refs/tags/0.1.0
      endpoint: rink72


# steps:
#   - checkout: self
#   - checkout: infrastructure
#   - pwsh: Write-Host Hello
#     displayName: Say hello
#     name: firstStep
# stages:
#   - stage: Deploy
#     displayName: Infrastructure deploy
#     jobs:
#     - template: ../../_templates/jobs/infrastructure-deploy.yml
#       parameters:
#         cloudType: GCP
#         service: labbox

#         environmentName: DINT
#         endpointName: ${{ variables.endpointDev }}
#         releaseStrategy: ${{ parameters.releaseStrategy }}
#         variables:
#           appServiceConfigPath: ${{ variables.appServiceConfigPath }}
#           appServiceArtifactPath: ${{ variables.appServiceArtifactPath }}
#           autoTestsConfigPath: ${{ variables.autoTestsConfigPath }}
#           autoTestsArtifactPath: ${{ variables.autoTestsArtifactPath }}
#           pmVersion: ${{ variables.pmVersion }}
